Update shark

diff --git a/shark b/shark
--- a/shark
+++ b/shark
@@ -1,4 +1,5 @@
 #!/data/data/com.termux/files/usr/bin/bash
+
 ##############################################
 #                                            #
 #             PROJECT: SHARK                 #
@@ -9,6 +10,143 @@
 #       created by :- a s h i s h            #
 #                                            #
 ##############################################
+
+#########
+# COLORS
+#########
+
+#colors
+white="\033[1;37m"                                          ##
+grey="\033[0;37m"                                           ##
+purple="\033[0;35m"                                         ##
+red="\033[1;31m"                                            ##
+green="\033[1;32m"                                          ##
+yellow="\033[1;33m"                                         ##
+purple="\033[0;35m"                                         ##
+cyan="\033[0;36m"                                           ##
+cyan1="\033[1;36m"                                          ##
+cafe="\033[0;33m"                                           ##
+fiuscha="\033[0;35m"                                        ##
+blue="\033[1;34m"                                           ##
+nc="\e[0m"                                                  ## 
+
+##########
+# VERSION
+##########
+
+VERSION="2.0.3"
+
+################
+# PRINT MESSAGE
+################
+
+msg() {
+	printf "${blue}[-] ${green}${1}\n${nc}"
+}
+
+function update() {
+	version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutrials/shark/master/shark | grep -w "VERSION=" | head -n1)
+	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
+	if [ "${1}" != "-u" ] || [ "${1}" != "--update" ]; then
+		[ ${latest_version} != ${VERSION} ] && echo && msg "shark update is available !!" && sleep 2.5 && echo && msg "Run shark -u , shark --update" && echo && exit 1;	       
+        fi
+}
+
+###########
+# INTERNET
+###########
+
+#check ineternet connectivity for update
+function internet() {
+ping -c 1 google.com > /dev/null 2>&1
+if [ $? -eq 0 -a ! "${1}" = "--update" ] && [ $? -eq 0 -a ! "$1" = "-u" ]; then
+        update
+fi
+}
+
+function check_net() {
+        ping -c 1 google.com > /dev/null 2>&1
+        if [[ "$?" != 0 ]]
+        then
+                error_msg "No internet"
+        exit 0
+        fi
+}
+
+function check_update() {	
+        check_net
+        version=$(curl -L -s https://raw.githubusercontent.com/Bhaviktutorials/shark/master/shark | grep -w "VERSION=" | head -n1)
+	latest_version=$(echo ${version} | sed -e 's/[^0-9]\+[^0-9]/ /g' | cut -d '"' -f1)
+        if [ ${latest_version} = ${VERSION} ];then		
+                echo -e "\tReading \tpackage \tlists... \tDone
+                         \tBuilding \tdependency \ttree       
+                         \tReading \tstate \tinformation... \tDone
+                         \tshark \tis \talready \tthe \tnewest \tversion \t($VERSION)." | awk '{$1=$1};1'
+	        exit 1
+	else
+		main_update
+		exit 1
+	fi
+}
+
+########
+# USAGE
+########
+
+usage() {
+        cat <<EOF
+Usage: $(basename $0) [OPTIONS] available
+shark - future of phishing is here,
+A shark is a tool that will help you \do Phishing \in an advanced way so no one checks and identify that you are doing phishing.
+Copyright 2020 <ashishsingh103020@gmail.com>
+Options:
+  -u, --update      Update shark
+  -v, --version     Display the current shark version installed on your device
+  -h, --help        Print this help message
+  -a, --assist      List detail discription of shark
+For additional info, see: http://github.com/Bhaviktutorials/shark
+EOF
+}
+
+###########
+# OPTS ARG
+###########
+
+#getopts argument
+while true; do
+        case "$1" in		
+                -u|--update)			
+	                check_update
+			;;
+
+                -h|--help)			
+                        usage       
+                        exit 1
+			;;
+
+                -v|--version)			
+                        printf "version $VERSION\n"
+                        exit 1
+                        ;;
+
+		-a|--assist)
+			assist
+			exit 1
+			;;
+			
+                -*)			
+                        echo "ERROR: unknown option '$1'" 1>&2
+                        echo "see '--help' for usage" 1>&2
+                        exit 1
+                        ;;
+
+                *)	
+                        f=$1
+                        break			
+                        ;;
+	esac
+        shift
+done
 
 
 clear
